CREATE TABLE IF NOT EXISTS ods.load_audit (
    id BIGSERIAL PRIMARY KEY,
    dataset_name TEXT NOT NULL,
    requested_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    completed_at TIMESTAMPTZ,
    request_params JSONB,
    status TEXT NOT NULL DEFAULT 'started',
    notes TEXT
);

CREATE TABLE IF NOT EXISTS ods.instrument (
    id BIGSERIAL PRIMARY KEY,
    symbol TEXT NOT NULL,
    asset_type TEXT NOT NULL,
    cusip TEXT,
    description TEXT,
    exchange TEXT,
    asset_main_type TEXT,
    asset_sub_type TEXT,
    quote_type TEXT,
    ssid BIGINT,
    realtime BOOLEAN,
    first_seen_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    last_seen_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    source_payload JSONB,
    UNIQUE (symbol, asset_type)
);

CREATE INDEX IF NOT EXISTS idx_instrument_symbol ON ods.instrument (symbol);

CREATE TABLE IF NOT EXISTS ods.instrument_fundamental_history (
    instrument_id BIGINT NOT NULL REFERENCES ods.instrument(id) ON DELETE CASCADE,
    as_of_time TIMESTAMPTZ NOT NULL,
    week_52_high DOUBLE PRECISION,
    week_52_low DOUBLE PRECISION,
    dividend_amount DOUBLE PRECISION,
    dividend_yield DOUBLE PRECISION,
    dividend_date TIMESTAMPTZ,
    pe_ratio DOUBLE PRECISION,
    peg_ratio DOUBLE PRECISION,
    pb_ratio DOUBLE PRECISION,
    pr_ratio DOUBLE PRECISION,
    pcf_ratio DOUBLE PRECISION,
    gross_margin_ttm DOUBLE PRECISION,
    gross_margin_mrq DOUBLE PRECISION,
    net_profit_margin_ttm DOUBLE PRECISION,
    net_profit_margin_mrq DOUBLE PRECISION,
    operating_margin_ttm DOUBLE PRECISION,
    operating_margin_mrq DOUBLE PRECISION,
    return_on_equity DOUBLE PRECISION,
    return_on_assets DOUBLE PRECISION,
    return_on_investment DOUBLE PRECISION,
    quick_ratio DOUBLE PRECISION,
    current_ratio DOUBLE PRECISION,
    interest_coverage DOUBLE PRECISION,
    total_debt_to_capital DOUBLE PRECISION,
    lt_debt_to_equity DOUBLE PRECISION,
    total_debt_to_equity DOUBLE PRECISION,
    eps_ttm DOUBLE PRECISION,
    eps_change_percent_ttm DOUBLE PRECISION,
    eps_change_year DOUBLE PRECISION,
    eps_change DOUBLE PRECISION,
    rev_change_year DOUBLE PRECISION,
    rev_change_ttm DOUBLE PRECISION,
    rev_change_in DOUBLE PRECISION,
    shares_outstanding DOUBLE PRECISION,
    market_cap_float DOUBLE PRECISION,
    market_cap DOUBLE PRECISION,
    book_value_per_share DOUBLE PRECISION,
    short_int_to_float DOUBLE PRECISION,
    short_int_day_to_cover DOUBLE PRECISION,
    div_growth_rate_3_year DOUBLE PRECISION,
    dividend_pay_amount DOUBLE PRECISION,
    dividend_pay_date TIMESTAMPTZ,
    beta DOUBLE PRECISION,
    vol_1_day_avg DOUBLE PRECISION,
    vol_10_day_avg DOUBLE PRECISION,
    vol_3_month_avg DOUBLE PRECISION,
    avg_10_days_volume BIGINT,
    avg_1_day_volume BIGINT,
    avg_3_month_volume BIGINT,
    declaration_date TIMESTAMPTZ,
    dividend_freq INTEGER,
    eps DOUBLE PRECISION,
    dtn_volume BIGINT,
    next_dividend_pay_date TIMESTAMPTZ,
    next_dividend_date TIMESTAMPTZ,
    fund_leverage_factor DOUBLE PRECISION,
    source_payload JSONB,
    PRIMARY KEY (instrument_id, as_of_time)
);

CREATE INDEX IF NOT EXISTS idx_instrument_fundamental_history_as_of_time
ON ods.instrument_fundamental_history (as_of_time DESC);

CREATE TABLE IF NOT EXISTS ods.quote_history (
    instrument_id BIGINT NOT NULL REFERENCES ods.instrument(id) ON DELETE CASCADE,
    as_of_time TIMESTAMPTZ NOT NULL,
    week_52_high DOUBLE PRECISION,
    week_52_low DOUBLE PRECISION,
    ask_mic_id TEXT,
    ask_price DOUBLE PRECISION,
    ask_size BIGINT,
    ask_time TIMESTAMPTZ,
    bid_mic_id TEXT,
    bid_price DOUBLE PRECISION,
    bid_size BIGINT,
    bid_time TIMESTAMPTZ,
    close_price DOUBLE PRECISION,
    high_price DOUBLE PRECISION,
    last_mic_id TEXT,
    last_price DOUBLE PRECISION,
    last_size BIGINT,
    low_price DOUBLE PRECISION,
    mark DOUBLE PRECISION,
    mark_change DOUBLE PRECISION,
    mark_percent_change DOUBLE PRECISION,
    net_change DOUBLE PRECISION,
    net_percent_change DOUBLE PRECISION,
    open_price DOUBLE PRECISION,
    post_market_change DOUBLE PRECISION,
    post_market_percent_change DOUBLE PRECISION,
    quote_time TIMESTAMPTZ,
    trade_time TIMESTAMPTZ,
    security_status TEXT,
    total_volume BIGINT,
    source_payload JSONB,
    PRIMARY KEY (instrument_id, as_of_time)
);

CREATE INDEX IF NOT EXISTS idx_quote_history_as_of_time
ON ods.quote_history (as_of_time DESC);
